# Generated by Django 3.2.10 on 2023-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/slider_image')),
                ('discount_del', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels')], max_length=100)),
                ('sale', models.IntegerField()),
                ('brand_name', models.CharField(max_length=200)),
                ('dicount', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
